language: python
python:
- '3.4'
- '3.5'
- '3.6'
install:
- pip install -r requirements.txt
- pip install coveralls
script:
- coverage run ./patchalerts/scanner.py
after_script:
- COVERALLS_PARALLEL=true coveralls
